"""
Test real implementation with web requests

marked as webreq, to easily discard
"""

import logging
from typing import Any

import pytest

from yfinance_tools.adapters import YFinanceAdapter
from yfinance_tools.domain import ISIN, AssetType, FinancialIdentifierEntry, IdentifierEntryDict
from yfinance_tools.domain.exceptions import YFinanceWebFetchError

# to flags all tests in the file
# pytestmark = pytest.mark.webreq


@pytest.fixture
def mock_fetch_isin_and_fast_info(mocker):
    """
    Factory fixture to mock YFAdapter._fetch_isin_and_fast_info staticmethod.

    Allows tests to pass a custom mapping of:
      {"name": (mock_fast_info_object, "ISIN_STRING")}
    """

    def _configure(
        name_map: dict[str, tuple[Any, str] | Exception] | None = None, default_isin_prefix: str = "US000000000"
    ):
        name_map = name_map or {}

        def side_effect(name: str, yf_ticker: str):
            # 1. If 'name' is specifically configured in the test, return that:
            print(f"==side effect: {name} / {yf_ticker}")

            if name in name_map:
                val = name_map[name]
                print(f"name_map: {val}")
                if isinstance(val, Exception):
                    raise val

                if isinstance(val, tuple):
                    return val

            assert "ERROR Fixture", 1 == 0
            # 2. Otherwise, generate a sensible default mock structure:
            # mock_fast_info = mocker.MagicMock(name=f"FastInfo_{name}")
            # mock_fast_info.quote_type = "EQUITY"
            # mock_fast_info.currency = "USD"

            # generated_isin = f"{default_isin_prefix}_{name}"
            # print(f"==mock_ff: {mock_fast_info}, generated isin {generated_isin}")
            # return mock_fast_info, generated_isin

        # Patch the class because it's a @staticmethod
        return mocker.patch.object(YFinanceAdapter, "_fetch_isin_and_fast_info", side_effect=side_effect)

    return _configure


def test_fetch_static_identifiers_mock_web(mocker, mock_fetch_isin_and_fast_info) -> None:
    data = {
        "apple": FinancialIdentifierEntry("AAPL"),
        "cac40": FinancialIdentifierEntry("CAC40"),
        "eurusd": FinancialIdentifierEntry("EURUSD"),
    }

    # Prepare custom _YFFastInfo mocks
    apple_fast_info = mocker.MagicMock(quote_type="EQUITY", currency="USD")
    cac_fast_info = mocker.MagicMock(quote_type="INDEX", currency="EUR")
    eurusd_fast_info = mocker.MagicMock(quote_type="currency", currency="EUR")

    mock_fetch_isin_and_fast_info(
        {
            "apple": (apple_fast_info, "US0378331005"),
            "cac40": (cac_fast_info, "FR0003500008"),
            "eurusd": (eurusd_fast_info, None),
        }
    )

    adapter = YFinanceAdapter()

    results: IdentifierEntryDict = adapter.fetch_static_identifiers(data)

    assert len(results) == 3
    assert results["apple"].asset_type == "EQUITY"
    assert results["eurusd"].asset_type == "FOREX"
    assert results["eurusd"].isin is None


@pytest.mark.webreq
def test_fetch_static_identifiers() -> None:

    data = {"apple": FinancialIdentifierEntry("AAPL")}
    adapter = YFinanceAdapter()

    results: IdentifierEntryDict = adapter.fetch_static_identifiers(data)

    assert len(results) == 1
    assert results["apple"] == FinancialIdentifierEntry("AAPL", AssetType.EQUITY, "USD", ISIN("US0378331005"))


@pytest.mark.webreq
def test_fetch_static_wrong_yf_ticker(caplog) -> None:
    caplog.set_level(logging.WARNING)

    data = {"apple": FinancialIdentifierEntry("AAAAA")}
    adapter = YFinanceAdapter()

    results = adapter.fetch_static_identifiers(data)

    assert len(results) == 0
    # generated by yfinance
    assert "Quote not found for symbol: AAAAA" in caplog.text
    # generated by my code
    assert "Error in fetching data for apple:AAAAA" in caplog.text
    # assert "Error in fetching data for AAAAA" in caplog.text


def test_no_isin_and_type_equivalence(mocker, mock_fetch_isin_and_fast_info) -> None:
    # return "currency" and isin '-'
    mock_fetch_isin_and_fast_info({"eurusd": (mocker.MagicMock(quote_type="currency", currency="USD"), "-")})
    adapter = YFinanceAdapter()

    results: IdentifierEntryDict = adapter.fetch_static_identifiers({"eurusd": FinancialIdentifierEntry("DUM")})

    assert len(results) == 1
    # isin = None, equivalence needed "currency" to "FOREX"
    assert results["eurusd"] == FinancialIdentifierEntry("DUM", AssetType.FOREX, "USD")


def test_fetch_return_invalid_format(mocker, mock_fetch_isin_and_fast_info, caplog):

    data = {"apple": FinancialIdentifierEntry("DUM"), "cac40": FinancialIdentifierEntry("DUM")}

    # Prepare custom _YFFastInfo mocks
    apple_fast_info = mocker.MagicMock(quote_type="INVALID", currency="USD")
    cac40_fast_info = mocker.MagicMock(quote_type="INDEX", currency="USD")

    mock_fetch_isin_and_fast_info(
        {
            "apple": (apple_fast_info, "US0378331005"),
            "cac40": (cac40_fast_info, "invalid-isin"),
        }
    )

    adapter = YFinanceAdapter()
    results: IdentifierEntryDict = adapter.fetch_static_identifiers(data)

    assert len(results) == 0
    assert "Invalid AssetType" in caplog.text
    assert "Invalid ISIN" in caplog.text


@pytest.mark.webreq
def test_partially_valid(caplog) -> None:
    caplog.set_level(logging.INFO)

    data = {"invalid": FinancialIdentifierEntry("AAAAA"), "eurusd": FinancialIdentifierEntry("EURUSD=X")}

    adapter = YFinanceAdapter()

    results: IdentifierEntryDict = adapter.fetch_static_identifiers(data)

    assert len(results) == 1
    assert "eurusd" in results.keys()

    # generated by yfinance
    assert "Quote not found for symbol: AAAAA" in caplog.text
    # generated by my code
    assert "request web fetch for: invalid eurusd" in caplog.text
    assert "Error in fetching data for invalid:AAAAA" in caplog.text


def test_partially_valid_mock(mocker, mock_fetch_isin_and_fast_info, caplog):

    mock_fetch_isin_and_fast_info(
        {
            "apple": (mocker.MagicMock(quote_type="EQUITY", currency="USD"), "US0378331005"),
            "cac40": YFinanceWebFetchError("Parsing Dummy Error Log"),
        }
    )

    adapter = YFinanceAdapter()
    results: IdentifierEntryDict = adapter.fetch_static_identifiers(
        {"apple": FinancialIdentifierEntry("DUM"), "cac40": FinancialIdentifierEntry("DUM")}
    )

    assert len(results) == 1
    assert "Parsing Dummy Error Log" in caplog.text


def test_fast_info_throw_unexpected_exception(mocker, caplog):

    adapter = YFinanceAdapter()
    mocker.patch.object(YFinanceAdapter, "_fetch_isin_and_fast_info", side_effect=RuntimeError("Unexpected Test Error"))

    with pytest.raises(RuntimeError, match="Unexpected Test Error"):
        adapter.fetch_static_identifiers(
            {"eurusd": FinancialIdentifierEntry("DUM"), "eurusd2": FinancialIdentifierEntry("DUM")}
        )

    # may want to change
    # results: IdentifierEntryDict = adapter.fetch_static_identifiers(
    #     {"eurusd": FinancialIdentifierEntry("DUM"), "eurusd": FinancialIdentifierEntry("EURUSD")}
    # )
    # assert len(results) == 0
    # assert "Unexpected Test Error" in caplog.text


def test_fetch_one_static_identifier_runtime_error(mocker, caplog):

    # mock a static method, class in first argument
    mocker.patch.object(
        YFinanceAdapter, "fetch_one_static_identifier", side_effect=RuntimeError("Unexpected error in YFinanceAdapter")
    )

    adapter = YFinanceAdapter()

    with pytest.raises(RuntimeError, match="Unexpected error in YFinanceAdapter"):
        adapter.fetch_static_identifiers({"cac40": FinancialIdentifierEntry("^FCHI")})

    # assert len(result) == 0
    # assert "Unexpected Error fetching cac40" in caplog.text
