"""
Test real implementation with web requests

marked as webreq, to easily discard
"""

import logging

import pytest

from yfinance_tools.adapters import YFinanceAdapter
from yfinance_tools.domain import ISIN, AssetType, FinancialIdentifierEntry, IdentifierEntryDict

# to flags all tests in the file
# pytestmark = pytest.mark.webreq


@pytest.mark.webreq
def test_fetch_static_identifiers() -> None:

    data = {"apple": FinancialIdentifierEntry("AAPL")}
    adapter = YFinanceAdapter()

    results: IdentifierEntryDict = adapter.get_static_identifiers(data)

    assert len(results) == 1
    assert results["apple"] == FinancialIdentifierEntry("AAPL", AssetType.EQUITY, "USD", ISIN("US0378331005"))


@pytest.mark.webreq
def test_fetch_static_wrong_yf_ticker(caplog) -> None:
    # not sure what is the default level
    caplog.set_level(logging.WARNING)

    data = {"apple": FinancialIdentifierEntry("AAAAA")}
    adapter = YFinanceAdapter()

    results = adapter.get_static_identifiers(data)

    assert len(results) == 0
    # generated by yfinance
    assert "Quote not found for symbol: AAAAA" in caplog.text
    # generated by my code
    assert "Error in fetching data for apple:AAAAA" in caplog.text
    # assert "Error in fetching data for AAAAA" in caplog.text


@pytest.mark.webreq
def test_fetch_missing_isin_and_equivalence() -> None:
    data = {"eurusd": FinancialIdentifierEntry("EURUSD=X")}
    adapter = YFinanceAdapter()

    results: IdentifierEntryDict = adapter.get_static_identifiers(data)

    assert len(results) == 1
    # isin = None, "currency" to "FOREX"
    assert results["eurusd"] == FinancialIdentifierEntry("EURUSD=X", AssetType.FOREX, "USD")


@pytest.mark.webreq
def test_partially_valid(caplog) -> None:
    caplog.set_level(logging.INFO)

    data = {"invalid": FinancialIdentifierEntry("AAAAA"), "eurusd": FinancialIdentifierEntry("EURUSD=X")}

    adapter = YFinanceAdapter()

    results: IdentifierEntryDict = adapter.get_static_identifiers(data)

    assert len(results) == 1

    # generated by yfinance
    assert "Quote not found for symbol: AAAAA" in caplog.text
    # generated by my code
    assert "request web fetch for: invalid eurusd" in caplog.text
    assert "Error in fetching data for invalid:AAAAA" in caplog.text
